MyAcademicProfile/app/urls.py
from django.urls import path
from app import views

urlpatterns = [
    path('', views.home, name='home'),
    path('ece-students/', views.students_list, name='students_list'),
    path('ece-students/<str:roll_no>/<str:dob>/<str:mother_name>', views.student_detail, name='student_detail'),
    path('<str:id>/registration/', views.registration, name="registration"),
    path('thank_you', views.thank_you, name='thank_you'),
    path('data_exist', views.data_exist, name='data_exist'),
    path('ece-students/login/<str:roll_no>', views.login, name='login')
]


MyAcademicProfile/faishal/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyAcademicProfile/app/forms.py
from django import forms

def validate_comma(value):
    if ',' in value:
        raise forms.ValidationError("comma is not allowed")
    return value

my_default_errors = {
    'required': 'This field is required',
    'invalid': 'Enter a valid Number'
}

class RegistrationForm(forms.Form):
    
    name = forms.CharField(max_length=100, validators=[validate_comma])
    roll_no = forms.CharField(max_length=100, validators=[validate_comma], widget=forms.TextInput(attrs={'placeholder': 'eg: 1604-21-735-000'}))
    dob = forms.DateField(widget=forms.TextInput(attrs={'placeholder': 'eg: 27/10/2003'}))
    email = forms.EmailField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'eg: example@gmail.com'}))
    gender = forms.CharField(max_length=15, validators=[validate_comma])
    religion = forms.CharField(max_length=15, validators=[validate_comma])
    blood_group = forms.CharField(max_length=10, validators=[validate_comma])
    father_name = forms.CharField(max_length=100, validators=[validate_comma])
    mother_name = forms.CharField(max_length=100, validators=[validate_comma])
    address = forms.CharField(max_length=200)
    image = forms.ImageField(required=False)
    phone_number = forms.CharField(max_length=12)

    sem1_sgpa = forms.FloatField(max_value=10, min_value=0, widget=forms.TextInput(attrs={'placeholder': 'eg: 4.04'}), error_messages=my_default_errors)

    sem2_sgpa = forms.FloatField(max_value=10, min_value=0, widget=forms.TextInput(attrs={'placeholder': 'eg: 4.04'}), error_messages=my_default_errors)

    sem3_sgpa = forms.FloatField(max_value=10, min_value=0, widget=forms.TextInput(attrs={'placeholder': 'eg: 4.04'}), error_messages=my_default_errors)

    sem4_sgpa = forms.FloatField(max_value=10, min_value=0, widget=forms.TextInput(attrs={'placeholder': 'eg: 4.04'}), error_messages=my_default_errors)

    sem5_sgpa = forms.FloatField(max_value=10, min_value=0, widget=forms.TextInput(attrs={'placeholder': 'eg: 4.04'}), error_messages=my_default_errors)

    sem6_sgpa = forms.FloatField(max_value=10, min_value=0, widget=forms.TextInput(attrs={'placeholder': 'eg: 4.04'}), error_messages=my_default_errors)

    sem7_sgpa = forms.FloatField(max_value=10, min_value=0, widget=forms.TextInput(attrs={'placeholder': 'eg: 4.04'}), error_messages=my_default_errors)

    sem8_sgpa = forms.FloatField(max_value=10, min_value=0, widget=forms.TextInput(attrs={'placeholder': 'eg: 4.04'}), error_messages=my_default_errors)

MyAcademicProfile/app/templates/app/data_exist.html
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
	<style>
		body{
			background: #F2ECBE;
		}
		header{
			text-shadow: 5px 5px 4px #9A3B3B;
			color: #C08261; 
			margin-top: 150px;
			text-align: center;
			font-size: 60px;
		}
		h1{
			text-align: center;
		}
		a{
			text-decoration: none;
			color: #C08261; 
		}
		a:hover{
			color: #9A3B3B;
		}
	</style>
</head>
<body>
	<header>
		<h1 >Already<br>Exist</h1>
	</header>
	<h1><a href="{% url "home" %}">Back to Home Page</a></h1>


</body>
</html>

MyAcademicProfile/app/templates/app/fake.html
<div class="container-fluid px-1 py-5 mx-auto">
    <div class="row d-flex justify-content-center">
        <div class="col-xl-7 col-lg-8 col-md-9 col-11 text-center">
                <form class="form-card" onsubmit="event.preventDefault()">

                    <div class="row justify-content-between text-left">
                        <label class="form-sub-heading"><b>Personal Information : </b></label>
                    </div>

                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Name<span class="text-danger"> *</span></label> <input type="text" name="name" maxlength="100" value="{{student.name}}" required id="id_name" > </div>
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Roll Number<span class="text-danger"> *</span></label> <input type="text" name="roll_no" placeholder="eg: 1604-21-735-000" maxlength="100" value="{{student.roll_no}}" required id="id_roll_no"></div>
                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Date of Birth<span class="text-danger"> *</span></label> <input type="text" name="dob" placeholder="eg: 27/10/2003" value="{{student.dob}}" required id="id_dob"> </div>
                        
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Blood Group<span class="text-danger"> *</span></label> <input type="text" name="blood_group" maxlength="10" value="{{student.blood_group}}" required id="id_blood_group"> </div>
                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Gender<span class="text-danger"> *</span></label> <input type="text" name="gender" maxlength="15" value="{{student.gender}}" required id="id_gender"> </div>
                        
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Religion<span class="text-danger"> *</span></label> <input type="text" name="religion" maxlength="15" value="{{student.religion}}" required id="id_religion"> </div>
                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Mother Name<span class="text-danger"> *</span></label> <input type="text" name="mother_name" maxlength="100" value="{{student.mother_name}}" required id="id_mother_name"> </div>
                        
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Father Name<span class="text-danger"> *</span></label> <input type="text" name="father_name" maxlength="100" value="{{student.father_name}}" required id="id_father_name"> </div>
                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Phone Number<span class="text-danger"> *</span></label> <input type="text" name="phone_number" maxlength="12" value="{{student.phone_number}}" required id="id_phone_number"> </div>
                        
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Email<span class="text-danger"> *</span></label> <input type="text" name="email" placeholder="eg: example@gmail.com" maxlength="100" value="{{student.email}}" required id="id_email"> </div>
                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-12 flex-column d-flex"> <label class="form-control-label px-3">Address<span class="text-danger"> *</span></label> <input type="text" name="address" maxlength="200" value="{{student.address}}" required id="id_address"> </div>
                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Profile Photo<span class="text-danger"> *</span></label> <input type="file" name="image" accept="image/*" id="id_image"> </div>
                        <div class="form-group col-sm-6 flex-column d-flex"><img src="{{student.image.url}}" alt="profile-photo"></div>
                    </div>
                    <div class="row justify-content-between text-left">
                    <label class="form-sub-heading"><b>Academic Information : </b></label>
                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Semester 1 SGPA<span class="text-danger"> *</span></label> <input type="text" name="sem1_sgpa" placeholder="eg: 4.04" value="{{student.sem1_sgpa}}" required id="id_sem1_sgpa"> </div>
                        
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Semester 2 SGPA<span class="text-danger"> *</span></label> <input type="text" name="sem2_sgpa" placeholder="eg: 4.04" value="{{student.sem2_sgpa}}" required id="id_sem2_sgpa"> </div>
                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Semester 3 SGPA<span class="text-danger"> *</span></label> <input type="text" name="sem3_sgpa" placeholder="eg: 4.04" value="{{student.sem3_sgpa}}" required id="id_sem3_sgpa">  </div>
                        
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Semester 4 SGPA<span class="text-danger"> *</span></label> <input type="text" name="sem4_sgpa" placeholder="eg: 4.04" value="{{student.sem4_sgpa}}" required id="id_sem4_sgpa">  </div>
                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Semester 5 SGPA<span class="text-danger"> *</span></label> <input type="text" name="sem5_sgpa" placeholder="eg: 4.04" value="{{student.sem5_sgpa}}" required id="id_sem5_sgpa">  </div>
                        
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Semester 6 SGPA<span class="text-danger"> *</span></label> <input type="text" name="sem6_sgpa" placeholder="eg: 4.04" value="{{student.sem6_sgpa}}" required id="id_sem6_sgpa">  </div>
                    </div>
                    <div class="row justify-content-between text-left">
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Semester 7 SGPA<span class="text-danger"> *</span></label> <input type="text" name="sem7_sgpa" placeholder="eg: 4.04" value="{{student.sem7_sgpa}}" required id="id_sem7_sgpa">  </div>
                        
                        <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Semester 8 SGPA<span class="text-danger"> *</span></label> <input type="text" name="sem8_sgpa" value="Faishal" value="{{student.sem8_sgpa}}" required id="id_sem8_sgpa">  </div>
                    </div>

                    <div class="row justify-content-end">
                        <div class="form-group col-sm-6">
                            <button type="submit" class="btn-block btn">Submit</button> 
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>





<div class="row justify-content-between text-left">
    <div class="form-group col-sm-6 flex-column d-flex"> 
        <label class="form-control-label px-3">Profile Photo<span class="text-danger"> *</span></label> 
        Currently: <a href="/media/images/default_image.png">images/default_image.png</a>
        <input type="checkbox" name="image-clear" id="image-clear_id">
        <label for="image-clear_id">Clear</label><br>
        Change:
        <input type="file" name="image" accept="image/*" id="id_image"> 
    </div>
</div>
                            

MyAcademicProfile/app/templates/app/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en"> 
<head>
  <!-- Design by foolishdeveloper.com -->
    <title>Login Page</title>
 
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <!--Stylesheet-->
    <link rel="stylesheet" type="text/css" href="{% static "app/login.css" %}">
</head>
<body>
    <div class="background">
        <div class="shape"></div> 
        <div class="shape"></div>
    </div>
    <form method='post'>
        {% csrf_token %}

        <h3>Login Here</h3>

        <label for="roll_no">Roll Number</label>
        <input type="text"   name='roll_no' value='{{roll_no}}'>

        <label for="dob">Date of Birth</label>
        <input type="text" placeholder="eg: YYYY-MM-DD" name='dob'>

        <label for="mother_name">Mother Name</label>
        <input type="text" placeholder=""  name='mother_name'>



        <button>Log In</button>
    </form>
</body>
</html>

MyAcademicProfile/app/templates/app/registration.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href='{% static "app/registration.css" %}'>
    <title>Registration Form</title>
  </head>
  <body>



    <ul>
        <li><a class="anchor" href="{% url "home" %}">Home</a></li>
        <li><a class="anchor" href="{% url "students_list" %}">Students List</a></li>
        <li class="dropdown">
            <a href="javascript:void(0)" class="dropbtn">Dropdown</a>
            <div class="dropdown-content">
                <a class="anchor" href="#">Link 1</a>
                <a class="anchor" href="#">Link 2</a>
                <a class="anchor" href="#">Link 3</a>
            </div>
        </li> 
    </ul>







    <form method='post' enctype="multipart/form-data">
        {% csrf_token %}
        

        
        <div class="container-fluid px-1 py-5 mx-auto">
            <div class="row d-flex justify-content-center">
                <div class="col-xl-7 col-lg-8 col-md-9 col-11 text-center">
                    <h1><b><u>Registraion Form</u></b></h1>
                        <form class="form-card" onsubmit="event.preventDefault()">

                            <div class="row justify-content-between text-left">
                                <label class="form-sub-heading"><b>Personal Information : </b></label>
                             </div>

                            <div class="row justify-content-between text-left">
                                <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Name<span class="text-danger"> *</span></label> {{ form.name }} </div>
                                <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Roll Number<span class="text-danger"> *</span></label> {{ form.roll_no }}</div>
                            </div>
                            <div class="row justify-content-between text-left">
                                <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Date of Birth<span class="text-danger"> *</span></label> {{ form.dob }} </div>
                                
                                <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Blood Group<span class="text-danger"> *</span></label> {{ form.blood_group }} </div>
                            </div>
                            <div class="row justify-content-between text-left">
                                <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Gender<span class="text-danger"> *</span></label> {{ form.gender }} </div>
                                
                                <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Religion<span class="text-danger"> *</span></label> {{ form.religion }} </div>
                            </div>
                            <div class="row justify-content-between text-left">
                                <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Mother Name<span class="text-danger"> *</span></label> {{ form.mother_name }} </div>
                                
                                <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Father Name<span class="text-danger"> *</span></label> {{ form.father_name }} </div>
                            </div>
                            <div class="row justify-content-between text-left">
                                <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Phone Number<span class="text-danger"> *</span></label> {{ form.phone_number }} </div>
                                
                                <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Email<span class="text-danger"> *</span></label> {{ form.email }} </div>
                            </div>
                            <div class="row justify-content-between text-left">
                                <div class="form-group col-12 flex-column d-flex"> <label class="form-control-label px-3">Address<span class="text-danger"> *</span></label> {{ form.address }} </div>
                            </div>
                            <div class="row justify-content-between text-left">
                                <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Profile Photo<span class="text-danger"> *</span></label> {{form.image}} </div>
                                {% if id != "fill" %}
                                    <div class="form-group col-sm-6 flex-column d-flex"><img  class="profile_img" src="{{student.image.url}}" alt="profile-photo"></div>
                                {% endif %}
                              
                            </div>
                            <div class="row justify-content-between text-left">
                               <label class="form-sub-heading"><b>Academic Information : </b></label>
                            </div>
                            <div class="row justify-content-between text-left">
                                <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Semester 1 SGPA<span class="text-danger"> *</span></label> {{ form.sem1_sgpa }}{{form.sem1_sgpa.errors}} </div>
                                
                                <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Semester 2 SGPA<span class="text-danger"> *</span></label> {{ form.sem2_sgpa }}{{form.sem2_sgpa.errors}} </div>
                            </div>
                            <div class="row justify-content-between text-left">
                                <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Semester 3 SGPA<span class="text-danger"> *</span></label> {{ form.sem3_sgpa }} {{form.sem3_sgpa.errors}} </div>
                                
                                <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Semester 4 SGPA<span class="text-danger"> *</span></label> {{ form.sem4_sgpa }}{{form.sem4_sgpa.errors}}  </div>
                            </div>
                            <div class="row justify-content-between text-left">
                                <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Semester 5 SGPA<span class="text-danger"> *</span></label> {{ form.sem5_sgpa }} {{form.sem5_sgpa.errors}} </div>
                                
                                <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Semester 6 SGPA<span class="text-danger"> *</span></label> {{ form.sem6_sgpa }} {{form.sem6_sgpa.errors}} </div>
                            </div>
                            <div class="row justify-content-between text-left">
                                <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Semester 7 SGPA<span class="text-danger"> *</span></label> {{ form.sem7_sgpa }} {{form.sem7_sgpa.errors}} </div>
                                
                                <div class="form-group col-sm-6 flex-column d-flex"> <label class="form-control-label px-3">Semester 8 SGPA<span class="text-danger"> *</span></label> {{ form.sem8_sgpa }} {{form.sem8_sgpa.errors}} </div>
                            </div>

                            <div class="row justify-content-end">
                                <div class="form-group col-sm-6">
                                    <button type="submit" class="btn-block btn">Submit</button> 
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
            
        
    </form>

  </body>
</html>



MyAcademicProfile/app/templates/app/sample.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">    
    <title>Registration Form</title>
  </head>
  <body>
    <form method='post'>

        <input type="hidden" name="csrfmiddlewaretoken" value="9M3CVAErmIzYrCVWrv4IWdyrA0bmw2WOMMzmEltMSnGGRHsdQ8WjPgQCwl3xJXRX">

        <div>
            <label for="id_name">Name:</label>
            <input type="text" name="name" maxlength="100" required id="id_name">
        </div>


        <div>
            <label for="id_roll_no">Roll no:</label>
            <input type="text" name="roll_no" maxlength="100" required id="id_roll_no">
        </div>


        <div>
            <label for="id_dob">Dob:</label>
            <input type="text" name="dob" required id="id_dob"> 
        </div>


        <div>
            <label for="id_email">Email:</label>
            <input type="email" name="email" maxlength="100" required id="id_email">   
        </div>


        <div>
            <label for="id_gender">Gender:</label>
            <input type="text" name="gender" maxlength="15" required id="id_gender">
        </div>


        <div>
            <label for="id_religion">Religion:</label>
            <input type="text" name="religion" maxlength="15" required id="id_religion"> 
        </div>
        

        <div>
            <label for="id_blood_group">Blood group:</label>
            <input type="text" name="blood_group" maxlength="10" required id="id_blood_group">
        </div>


        <div>
            <label for="id_father_name">Father name:</label>
            <input type="text" name="father_name" maxlength="100" required id="id_father_name">
        </div>


        <div>
            <label for="id_mother_name">Mother name:</label>
            <input type="text" name="mother_name" maxlength="100" required id="id_mother_name">
        </div>


        <div>
            <label for="id_address">Address:</label>
            <input type="text" name="address" maxlength="200" required id="id_address">
        </div>


        <div>
            <label for="id_phone_number">Phone number:</label>
            <input type="text" name="phone_number" maxlength="12" required id="id_phone_number">
        </div>


        <div>
            <label for="id_sem1_sgpa">Sem1 sgpa:</label>
            <input type="number" name="sem1_sgpa" min="0" max="10" step="any" required id="id_sem1_sgpa">
        </div>


        <div>
            <label for="id_sem2_sgpa">Sem2 sgpa:</label>
            <input type="number" name="sem2_sgpa" min="0" max="10" step="any" required id="id_sem2_sgpa">
        </div>


        <div>
            <label for="id_sem3_sgpa">Sem3 sgpa:</label>
            <input type="number" name="sem3_sgpa" min="0" max="10" step="any" required id="id_sem3_sgpa">
        </div>
    

        <div>
            <label for="id_sem4_sgpa">Sem4 sgpa:</label>
            <input type="number" name="sem4_sgpa" min="0" max="10" step="any" required id="id_sem4_sgpa">
        </div>


        <div>
            <label for="id_sem5_sgpa">Sem5 sgpa:</label>
            <input type="number" name="sem5_sgpa" min="0" max="10" step="any" required id="id_sem5_sgpa">
        </div>

        
        <div>
            <label for="id_sem6_sgpa">Sem6 sgpa:</label>
            <input type="number" name="sem6_sgpa" min="0" max="10" step="any" required id="id_sem6_sgpa">
        </div>


        <div>
            <label for="id_sem7_sgpa">Sem7 sgpa:</label>
            <input type="number" name="sem7_sgpa" min="0" max="10" step="any" required id="id_sem7_sgpa">
        </div>


        <div>
            <label for="id_sem8_sgpa">Sem8 sgpa:</label>
            <input type="number" name="sem8_sgpa" min="0" max="10" step="any" required id="id_sem8_sgpa">
    
        </div>
        
    </form>

  </body>
</html>



MyAcademicProfile/app/templates/app/students_list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="{% static "app/students_list.css" %}">
    <title>Students List</title>
</head>
<style>
    button.btn {
        display:block;
        margin-top:10px;
        margin-right:20px;
        background-color: #C08261;
        border: none;
        color: white;
        padding: 16px 25px;
        font-size: 16px;
        cursor: pointer;
        float:right;
        border-radius:10px;
    }
      
    /* Darker background on mouse-over */
    .btn:hover {
        transform:scale(1.1);
    }
    
</style>
<body>
    <nav class="navbar">
        <ul>
          <li class="list"><a class="anchor" href="{% url "home" %}">Home</a></li>
          <li class="dropdown list">
              <a class="anchor" href="javascript:void(0)" class="dropbtn">Branch</a> 
              <div class="dropdown-content">
                  <a class="anchor" href="{% url "students_list" %}">ECE</a>
                  <a class="anchor" href="#">CSE</a>
                  <a class="anchor" href="#">IT</a>
              </div>
          </li>
          <li class="list"><a class="anchor" href="#">About</a></li>
        </ul>
    </nav>
    <a href='{% url "registration" "fill"%}'>
        <button class="btn"><i class="fa fa-plus"></i> Add</button>
    </a>  

    <div class="container">
        <h2>ECE-B STUDENTS <small>2021-2025</small></h2>
        <ul class="responsive-table">
            <li class="table-header">
                <div class="col col-1">Roll No</div>
                <div class="col col-2">Student Name</div>
                <div class="col col-2">Avg SGPA</div>
                {% comment %} <div class="col col-3">Avg Sgpa</div> {% endcomment %}
            </li>
            {% for student in students %}
                <a class='mylinkclass' href='{% url "login" student.roll_no %}'>
                    <li class="table-row">
                        <div class="col col-1" data-label="Roll Number">{{student.roll_no}}</div>
                        <div class="col col-2" data-label="Student Name">{{student.name}}</div>
                        <div class="col col-2" data-label="Student Name">{{student.sem1_sgpa}}</div>
                        {% comment %} <div class="col col-3" data-label="Amount">{{student_avg_sgpa}}</div> {% endcomment %}
                    </li>
                </a>
          {% endfor %}
        </ul>
      </div>
</body>
</html>



{% comment %} 


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static "app/students_list.css" %}">
    <title>Students List</title>
</head>
<body>
    <table>
        <tr>
          <th>Roll No</th>
          <th>Name</th>
          <th>Details</th>
        </tr>
        {% for student in students %}
            <tr>
                <td>{{student.roll_no}}</td>
                <td>{{student.name}}</td>
                <td><a href="{% url "student_detail" student.roll_no %}">Click here</a></td>
            </tr>
        {% endfor %}
      </table>
</body>
</html> {% endcomment %}